name: CI Pipeline

on:
  push:
    branches:
      - dev
      - main
      - send-comments
  pull_request:
    branches:
      - dev
      - main
      - send-comments

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'

      - name: Install and Build Front-End
        run: |
          npm install
          npm run build
        working-directory: ./front

      - name: Install and Build Back-End
        run: |
          npm install
          npm start
        working-directory: ./server

      - name: Run Front-End Tests
        run: npm test
        working-directory: ./front

      - name: Run Back-End Tests
        run: |
          npm install
          npm test
        working-directory: ./server
        
